INSERT INTO TAX_CATEGORY(ID, CATEGORY, TAX) VALUES (1, 'A', 10);
INSERT INTO TAX_CATEGORY(ID, CATEGORY, TAX) VALUES (2, 'B', 20);
INSERT INTO TAX_CATEGORY(ID, CATEGORY, TAX) VALUES (3, 'C', 0);

INSERT INTO PRODUCT(ID, TAX_CATEGORY_ID, NAME, PRICE) VALUES (1, 1, 'MILK 1 L', 40);
INSERT INTO PRODUCT(ID, TAX_CATEGORY_ID, NAME, PRICE) VALUES (2, 1, 'SUFFOLA 1 L', 80);
INSERT INTO PRODUCT(ID, TAX_CATEGORY_ID, NAME, PRICE) VALUES (3, 2, 'BADAM 1 KG', 100);
INSERT INTO PRODUCT(ID, TAX_CATEGORY_ID, NAME, PRICE) VALUES (4, 3, 'RICE 1 KG', 60);

