CREATE TABLE TAX_CATEGORY (
    ID NUMBER(19)  NOT NULL,
    CATEGORY VARCHAR2(50) NOT NULL,
    TAX NUMBER(10) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT (
    ID NUMBER(19)  NOT NULL,
    TAX_CATEGORY_ID NUMBER(19) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    PRICE NUMBER(100) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (TAX_CATEGORY_ID) REFERENCES TAX_CATEGORY(ID)
);